/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * India Fuel Price Tracker API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get today's fuel prices for all cities
 */
export const GetFuelPricesResponseItem = zod.object({
  city: zod.string(),
  state: zod.string(),
  petrolPrice: zod.number(),
  dieselPrice: zod.number(),
  petrolChange: zod.number(),
  dieselChange: zod.number(),
  updatedAt: zod.string(),
});
export const GetFuelPricesResponse = zod.array(GetFuelPricesResponseItem);

/**
 * @summary Get 30-day price trend for a city
 */
export const GetCityTrendParams = zod.object({
  city: zod.coerce.string(),
});

export const GetCityTrendResponseItem = zod.object({
  date: zod.string(),
  petrolPrice: zod.number(),
  dieselPrice: zod.number(),
});
export const GetCityTrendResponse = zod.array(GetCityTrendResponseItem);
