/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * India Fuel Price Tracker API
 * OpenAPI spec version: 0.1.0
 */

export interface PriceTrendPoint {
  date: string;
  petrolPrice: number;
  dieselPrice: number;
}
